export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USER_INFO = 'USER_INFO';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const LOGOUT = 'LOGOUT';
